project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: 'RegRed'
  site-url: ''
  repo-url: /
  
  page-footer:
    right: "This page is built with üßâÔ∏è and [Quarto](https://quarto.org/)"
    left: "**Modelling of Biodiversity Lab** (MOBI Lab) -- **Faculty of Environmental Sciences** (F≈ΩP ƒåZU)"
    background: "#f2f2f2"
    center: 'This work is licensed under <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International</a><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"> '
    
  sidebar:
    logo: 'images/other_random_logo_regred.png'
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://github.com/RegRed-project
        text: 'RegRed'
      - icon: github
        href: https://github.com/RegRed-project/data_extraction_protocol
        text: 'GitHub'

    style: docked
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: sections/roles_team_and_responsibilities.qmd
        text: Roles, team and responsibilities
      - href: sections/resources.qmd
        text: Tools and resources
      - section: Workflow
        contents:
          - section: For data extractors #sections/workflows/for_data_extractors/steps.qmd
            contents:
              - href: sections/workflows/for_data_extractors/step_1.qmd
                text: 1. Select a source
              - href: sections/workflows/for_data_extractors/step_2.qmd
                text: 2. Extract the data
              - href: sections/workflows/for_data_extractors/step_3.qmd
                text: 3. Store the extracted data

          - href: sections/workflows/for_nrl_data_harmoniser/steps.qmd
            text: For NRL data harmoniser
          - href: sections/workflows/for_spatial_data_generator/steps.qmd
            text: For spatial data generator
          - href: sections/workflows/for_taxonomy_harmoniser/steps.qmd
            text: For taxonomy harmoniser
      - section: Appendices
        contents:
          - href: sections/appendices/extraction_template_definitions.qmd
            text: Extraction template definitions
          - href: sections/appendices/controlled_vocabulary.qmd
            text: Controlled vocabulary
          - href: sections/appendices/citation_rules.qmd
            text: Citation rules
          - href: sections/appendices/iucn_regional_categories.qmd
            text: IUCN regional categories  
      - href: sections/faq.qmd
        text: FAQ

format:
  html:
    mermaid:
      theme: neutral
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
    code-copy: true
    code-overflow: wrap
    # toc: true
    # toc-location: left
    filters:
      - highlight-text
    include-in-header:
      - text: |
          <style>
            .light-content a,
            .dark-content a {
              color: inherit;
            }
          </style>
    grid:
      sidebar-width: 500px
      body-width: 1200px
      margin-width: 0px
      gutter-width: 1.5rem
